CREATE DATABASE jsdpaymentdb;

USE jsdpaymentdb;

CREATE TABLE IF NOT EXISTS `jsdpaymentdb`.`01_USER` (
  `USER_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PWD` VARCHAR(150) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `STATUS` CHAR(1) NOT NULL,
  `IND_PWD_TEMP` CHAR(1),
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;

